# Generated by Django 4.0 on 2025-01-26 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('original_image', models.ImageField(upload_to='uploaded_images/')),
                ('encoded_image', models.ImageField(blank=True, null=True, upload_to='encoded_images/')),
                ('message', models.TextField(blank=True, null=True)),
                ('bits_used', models.IntegerField(default=1)),
                ('date_uploaded', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
